spring:
  datasource:
    url: jdbc:mysql://10.65.215.12:3306?user=root&password=wch123&useUnicode=true&characterEncoding=utf-8
server:
  servlet:
    context-path: /rumormonger
#regex:
#  schema: payment2
#  table: tb_party_payment_funds
#logging:
#   level:
#      com.wch: debug